name: openweather
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  # Networking
  dio: 3.0.9
  retrofit: 1.3.4

  # Json
  json_serializable: 3.3.0
  dio_flutter_transformer: 3.0.2

  # Service locator
  get_it: 4.0.2

  # BLoC
  bloc_provider: 0.7.0

  # Rx
  rxdart: 0.24.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: 1.3.4+1
  build_runner: 1.9.0

flutter:
  uses-material-design: true